### ISSUE TITLE
Running in debug mode will only preserve last HOME

### ISSUE THREAD

**Issue by Whissi** [mgorny/gemato#10]
While trying to debug a WKD issue I noticed that `dirmngr.log` did only contain debug information showing key fetch from keyserver -- nothing about WKD at all.

I logged `OpenPGPEnvironment::_init__` calls and noticed that each gemato run will create and use multiple HOMEs but only the last one will be preserved.

Changing `debug_file` value to a fixed value in mentioned constructor allowed me to get dirmngr logs showing WKD operations.

**Comment by mgorny** [comment]
Ok, I see the problem. We need to use two homedirs to workaround GPG limitations. The problem is that the debug flag is not passed to sub-env. I will fix that.
