### ISSUE TITLE
cannot refresh wkd behing a proxy

### ISSUE THREAD

**Issue by fepitre** [mgorny/gemato#14]
`gpg` is failing to locate keys behing proxy. For example, in case of Gentoo, it fails to locate keys with mail: `repomirrorci@gentoo.org`, `infrastructure@gentoo.org` and `releng@gentoo.org`.

Maybe it's worth it to add a fallback implementation than `gpg`? Maybe using requests on a keyserver?

Related `gpg`: https://dev.gnupg.org/T3065#111023
Related `gentoo` work: https://github.com/gentoo/portage/pull/607

**Comment by mgorny** [comment]
I'm presuming gemato end is fixed now.
