### ISSUE TITLE
gemato fails on systems which have no ipv6 support

### ISSUE THREAD

**Issue by Polynomial-C** [mgorny/gemato#3]
This happens on one of my systems that has no ipv6 support during `emerge --sync`:
```
sent 31.81K bytes  received 6.82M bytes  1.25M bytes/sec
total size is 224.29M  speedup is 32.71
INFO:root:Refreshing keys from keyserver...
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.5/gemato", line 11, in <module>
    load_entry_point('gemato==10.3', 'console_scripts', 'gemato')()
  File "/usr/lib64/python3.5/site-packages/gemato/cli.py", line 403, in setuptools_main
    sys.exit(main(sys.argv))
  File "/usr/lib64/python3.5/site-packages/gemato/cli.py", line 398, in main
    return vals.func(vals, argp)
  File "/usr/lib64/python3.5/site-packages/gemato/cli.py", line 62, in do_verify
    env.refresh_keys()
  File "/usr/lib64/python3.5/site-packages/gemato/openpgp.py", line 219, in refresh_keys
    raise RuntimeError('Unable to refresh keys: {}'.format(err.decode('utf8')))
RuntimeError: Unable to refresh keys: gpg: refreshing 4 keys from hkps://hkps.pool.sks-keyservers.net
gpg: keyserver refresh failed: Address family not supported by protocol
 
q: Updating ebuild cache in /var/portage ...
q: Finished 37364 entries in 0.362387 seconds
 
Action: sync for repo: gentoo, returned code = 1
```
And indeed, running `gpg --refresh-keys --keyserver hkps://ipv6.pool.sks-keyservers.net` manually yields to the same error message.
[Arfrever] suggested to ask for custom keyserver support in gemato. Is this a reasonable request?

**Comment by Arfrever** [comment]
Alternatively:
Detect if IPv4 is supported.
Detect if IPv6 is supported.
If IPv4 is supported and IPv6 is supported, set `keyserver hkps://hkps.pool.sks-keyservers.net` in generated `gpg.conf`.
If IPv4 is supported and IPv6 is NOT supported, set `keyserver hkps://ipv4.pool.sks-keyservers.net` in generated `gpg.conf`.
If IPv4 is NOT supported and IPv6 is supported, set `keyserver hkps://ipv6.pool.sks-keyservers.net` in generated `gpg.conf`.
If IPv4 is NOT supported and IPv6 is NOT supported, print error.

**Comment by mgorny** [comment]
Looks like a bug in gnupg. Please report it there first, and let's see what they say.

**Comment by mgorny** [comment]
Let's continue this on https://bugs.gentoo.org/646194. I'll keep the bug open for people who look here first.

**Comment by mgorny** [comment]
This has been fixed in GnuPG, so let's continue on the Gentoo bug.
