### ISSUE TITLE
gemato verify - "No public key" issue

### ISSUE THREAD

**Issue by ivlar1991** [mgorny/gemato#4]
> root@host1 /tmp # gemato verify /usr/portage
> ERROR:root:OpenPGP verification failed:
> gpg: Signature made Thu 01 Feb 2018 01:08:17 PM UTC
> gpg:                using RSA key E1D6ABB63BFCFB4BA02FDF1CEC590EEAC9189250
> gpg: Can't check signature: No public key

Could anyone please help?

**Comment by ivlar1991** [comment]
Maybe this bug? https://bugs.gentoo.org/646194

**Comment by mgorny** [comment]
You either need to pass it public key file as `-K` or `gpg --recv-keys ...` the valid key.

**Comment by ivlar1991** [comment]
@mgorny,

When I do this:
# gemato verify -K /var/lib/gentoo/gkeys/keyrings/gentoo/release/pubring.gpg -s /usr/portage
It works properly, and `echo $?` equals 0 in bash.

But when I do
# eix-sync
I get everytime this output:
> ERROR:root:OpenPGP verification failed:
> gpg: Signature made Thu 01 Feb 2018 03:08:18 PM UTC
> gpg:                using RSA key E1D6ABB63BFCFB4BA02FDF1CEC590EEAC9189250
> gpg: Can't check signature: No public key

As far as I know, in the `eix-sync` case gemato should be launched by sys-apps/portage with valid keys from /usr/share/portage/config/repos.conf But this does not happen.

**Comment by ivlar1991** [comment]
@mgorny,

UPDATE: I found the root cause of the issue! I had default /usr/share/portage/config/repos.conf installed by portage and custom /etc/portage/repos.conf/gentoo.conf from this Wiki:

[DEFAULT]
main-repo = gentoo
[gentoo]
location = /usr/portage
sync-type = rsync
sync-uri = rsync://rsync.gentoo.org/gentoo-portage
auto-sync = yes

But when I removed  /etc/portage/repos.conf/gentoo.conf gemato became working fine! So Gentoo Wiki probably contains a critical issue.

**Comment by ivlar1991** [comment]
https://wiki.gentoo.org/wiki//etc/portage/repos.conf

There is an issue. /etc/portage/repos.conf/gentoo.conf should
either not exist
or contain the same content as in /usr/share/portage/config/repos.conf

**Comment by mgorny** [comment]
But that shouldn't wipe the original entry. Feel free to report a Portage bug.
