### ISSUE TITLE
hkps on port 80

### ISSUE THREAD

**Issue by osburn-sharp** [mgorny/gemato#6]
Great step forward, but even better if you allowed the use of a conventional port for hkps://hkps.pool.sks-keyservers.net. 443 or even 80. Should be a simple change? Currently I am disabling it because I don't really like opening ports for things that are not even in /etc/services.

**Comment by mgorny** [comment]
Gemato doesn't use any ports. All network interaction is done via gpg, so it's a problem with your gpg config.
